name: Build npm package
on:
  push:
    branches:
      - '**'
jobs:
  build:
    if: contains(github.event.head_commit.message, '🔖')
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v3
      - name: 🔨 Setup node (github registry)
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: 👷 Install
        run: npm ci
      - name: 📦️ Publish package (npmjs)
        if: github.ref_name == 'master'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      - name: 📦️ Publish tagged package (npmjs)
        if: github.ref_name != 'master'
        run: npm publish --tag ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
